include:
  - ../common/networks.yaml

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:${HOMEPAGE_VERSION:-latest}
    container_name: homepage
    restart: unless-stopped
    labels:
      wud.tag.include: '^v\d+\.\d+\.\d+$'
      wud.link.template: 'https://github.com/gethomepage/homepage/releases/tag/$${original}'
    environment:
      PUID: 1000
      PGID: 1000
      LOG_TARGETS: stdout
      HOMEPAGE_ALLOWED_HOSTS: homepage.sdf1.site
      HOMEPAGE_FILE_AUTHENTIK_PASS: /run/secrets/authentik_pass
      HOMEPAGE_FILE_AUTHENTIK_API_TOKEN: /run/secrets/authentik_api_token
      HOMEPAGE_FILE_BAZARR_KEY: /run/secrets/bazarr_key
      HOMEPAGE_FILE_NPM_PASS: /run/secrets/npm_pass
      HOMEPAGE_FILE_PAPERLESS_KEY: /run/secrets/paperless_key
      HOMEPAGE_FILE_PLEX_KEY: /run/secrets/plex_key
      HOMEPAGE_FILE_PROWLARR_KEY: /run/secrets/prowlarr_key
      HOMEPAGE_FILE_RADARR_KEY: /run/secrets/radarr_key
      HOMEPAGE_FILE_SABNZBD_KEY: /run/secrets/sabnzbd_key
      HOMEPAGE_FILE_SONARR_KEY: /run/secrets/sonarr_key
      HOMEPAGE_FILE_SYNOLOGY_PASS: /run/secrets/synology_pass
      HOMEPAGE_FILE_TAILSCALE_KEY: /run/secrets/tailscale_key
      HOMEPAGE_FILE_TAUTULLI_KEY: /run/secrets/tautulli_key
      HOMEPAGE_FILE_TRANSMISSION_PASS: /run/secrets/transmission_pass
      HOMEPAGE_FILE_TRUENAS_KEY: /run/secrets/truenas_key
      HOMEPAGE_FILE_UNIFI_UCG_MAX_KEY: /run/secrets/unifi_ucg_max_key
      HOMEPAGE_FILE_HOMEBOX_PASS: /run/secrets/homebox_pass
      HOMEPAGE_FILE_PROXMOX_PASS: /run/secrets/proxmox_token
      HOMEPAGE_FILE_HA_TOKEN: /run/secrets/homeassistant_token
      HOMEPAGE_FILE_BESZEL_PASS: /run/secrets/beszel_pass
      HOMEPAGE_FILE_IMMICH_KEY: /run/secrets/immich_key
    volumes:
      - /opt/appdata/homepage/main:/app/config
      - /opt/appdata/homepage/tls:/app/config/tls
    networks:
      - default
      - homelab
    secrets:
      - authentik_pass
      - authentik_api_token
      - bazarr_key
      - npm_pass
      - paperless_key
      - plex_key
      - prowlarr_key
      - radarr_key
      - sabnzbd_key
      - sonarr_key
      - synology_pass
      - tailscale_key
      - tautulli_key
      - transmission_pass
      - truenas_key
      - unifi_ucg_max_key
      - homebox_pass
      - proxmox_token
      - homeassistant_token
      - beszel_pass
      - immich_key
  homepage-public:
    image: ghcr.io/gethomepage/homepage:${HOMEPAGE_VERSION:-latest}
    container_name: homepage-public
    restart: unless-stopped
    labels:
      wud.watch: false
    environment:
      LOG_TARGETS: stdout
      PUID: 1000
      PGID: 1000
      HOMEPAGE_ALLOWED_HOSTS: home.sdf1.rampant.io,homepage-public:3000
      HOMEPAGE_FILE_AUTHENTIK_PASS: /run/secrets/authentik_pass
      HOMEPAGE_FILE_PAPERLESS_KEY: /run/secrets/paperless_key
      HOMEPAGE_FILE_HA_TOKEN: /run/secrets/homeassistant_token
      HOMEPAGE_FILE_IMMICH_KEY: /run/secrets/immich_key
      HOMEPAGE_FILE_PROXMOX_PASS: /run/secrets/proxmox_token
    volumes:
      - /opt/appdata/homepage/public:/app/config
    networks:
      - default
      - homelab
    secrets:
      - authentik_pass
      - paperless_key
      - homeassistant_token
      - immich_key
      - proxmox_token
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:${PROXY_VERSION:-latest}
    container_name: homepage-dockerproxy
    restart: unless-stopped
    labels:
      wud.tag.include: '^v\d+\.\d+\.\d+$'
    environment:
      - CONTAINERS=1
      - SERVICES=1
      - TASKS=1
      - POST=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - default

secrets:
  authentik_pass:
    file: /opt/appdata/homepage/secrets/authentik_pass
  authentik_api_token:
    file: /opt/appdata/homepage/secrets/authentik_api_token
  bazarr_key:
    file: /opt/appdata/homepage/secrets/bazarr_key
  calibre_pass:
    file: /opt/appdata/homepage/secrets/calibre_pass
  npm_pass:
    file: /opt/appdata/homepage/secrets/npm_pass
  paperless_key:
    file: /opt/appdata/homepage/secrets/paperless_key
  plex_key:
    file: /opt/appdata/homepage/secrets/plex_key
  prowlarr_key:
    file: /opt/appdata/homepage/secrets/prowlarr_key
  radarr_key:
    file: /opt/appdata/homepage/secrets/radarr_key
  sabnzbd_key:
    file: /opt/appdata/homepage/secrets/sabnzbd_key
  sonarr_key:
    file: /opt/appdata/homepage/secrets/sonarr_key
  synology_pass:
    file: /opt/appdata/homepage/secrets/synology_pass
  tailscale_key:
    file: /opt/appdata/homepage/secrets/tailscale_key
  tautulli_key:
    file: /opt/appdata/homepage/secrets/tautulli_key
  transmission_pass:
    file: /opt/appdata/homepage/secrets/transmission_pass
  transmission_user:
    file: /opt/appdata/homepage/secrets/transmission_user
  truenas_key:
    file: /opt/appdata/homepage/secrets/truenas_key
  unifi_ucg_max_key:
    file: /opt/appdata/homepage/secrets/unifi_ucg_max_key
  homebox_pass:
    file: /opt/appdata/homepage/secrets/homebox_pass
  proxmox_token:
    file: /opt/appdata/homepage/secrets/proxmox_token
  homeassistant_token:
    file: /opt/appdata/homepage/secrets/homeassistant_token
  beszel_pass:
    file: /opt/appdata/homepage/secrets/beszel_pass
  immich_key:
    file: /opt/appdata/homepage/secrets/immich_key

networks:
  default:
