# https://github.com/gitpod-io/openvscode-server
include:
  - ../common/networks.yaml
services:
  code-server:
    build:
      context: .
    container_name: vs-code-server
    restart: unless-stopped
    expose:
      - "3000"
    volumes:
      - /opt/code_workspace:/home/workspace
    networks:
      - homelab