# https://homebox.software/en/
# https://github.com/sysadminsmedia/homebox
# Port 7745

include:
  - ../common/networks.yaml

services:
  homebox:
    image: ghcr.io/sysadminsmedia/homebox:latest
    container_name: homebox
    restart: unless-stopped
    depends_on:
      - db
    env_file: /opt/appdata/homebox/homebox.env
    environment:
      HBOX_LOG_LEVEL: info
      HBOX_LOG_FORMAT: text
      HBOX_WEB_MAX_FILE_UPLOAD: 100
      HBOX_OPTIONS_ALLOW_REGISTRATION: false
      HBOX_OPTIONS_ALLOW_ANALYTICS: true
      HBOX_DATABASE_DRIVER: postgres
      HBOX_DATABASE_HOST: db
      HBOX_DATABASE_PORT: 5432
      HBOX_DATABASE_USERNAME: homebox
      HBOX_DATABASE_DATABASE: homebox
      HBOX_DATABASE_SSL_MODE: disable
    networks:
      - default
      - homelab
    volumes:
      - /opt/appdata/homebox/data:/data
  db:
    image: docker.io/library/postgres:16-bookworm
    container_name: homebox-db
    restart: unless-stopped
    user: "1000:1000"
    environment:
      POSTGRES_DB: homebox
      POSTGRES_USER: homebox
      POSTGRES_PASSWORD_FILE: /run/secrets/db_pass
    volumes:
      - /opt/appdata/homebox/db/pg16:/var/lib/postgresql/data
    networks:
      - default
    secrets:
      - db_pass

networks:
  default:

secrets:
  db_pass:
    file: /opt/appdata/homebox/secrets/db_pass
