# https://homebox.software/en/
# https://github.com/sysadminsmedia/homebox
# Port 7745

include:
  - ../common/networks.yaml

services:
  homebox:
    image: ghcr.io/sysadminsmedia/homebox:${HOMEBOX_VERSION:-latest}
    container_name: homebox
    restart: unless-stopped
    depends_on:
      - db
    labels:
      wud.tag.include: '^\d+\.\d+\.\d+$'
    env_file: /opt/appdata/homebox/secrets/secrets.env
    environment:
      HBOX_LOG_LEVEL: info
      HBOX_LOG_FORMAT: text
      HBOX_WEB_MAX_FILE_UPLOAD: 100
      HBOX_OPTIONS_ALLOW_REGISTRATION: false
      HBOX_OPTIONS_ALLOW_ANALYTICS: true
      HBOX_DATABASE_DRIVER: postgres
      HBOX_DATABASE_HOST: db
      HBOX_DATABASE_PORT: 5432
      HBOX_DATABASE_USERNAME: homebox
      HBOX_DATABASE_DATABASE: homebox
      HBOX_DATABASE_SSL_MODE: disable
    networks:
      - default
      - homelab
    volumes:
      - /opt/appdata/homebox/data:/data
  db:
    image: docker.io/library/postgres:${PGSQL_VERSION:-16-bookworm}
    container_name: homebox-db
    restart: unless-stopped
    user: "1000:1000"
    environment:
      POSTGRES_DB: homebox
      POSTGRES_USER: homebox
      POSTGRES_PASSWORD_FILE: /run/secrets/db_pass
    labels:
      wud.watch: false
      docker-volume-backup.exec-label: "homebox"
      docker-volume-backup.archive-pre: /bin/sh -c 'pg_dumpall -U homebox --clean --file=/backup/homebox_db.sql'
    volumes:
      - /opt/appdata/homebox/db/pg16:/var/lib/postgresql/data
      - /opt/appdata/homebox/db/backup:/backup
    networks:
      - default
    secrets:
      - db_pass

networks:
  default:

secrets:
  db_pass:
    file: /opt/appdata/homebox/secrets/db_pass
