include:
  - ../common/networks.yaml
services:
  broker:
    image: docker.io/library/redis:7
    container_name: paperless-broker
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - default

  db:
    image: docker.io/library/postgres:16-bookworm
    container_name: paperless-db
    restart: unless-stopped
    user: "1000:1000"
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD_FILE: /run/secrets/db_pass
    labels:
      docker-volume-backup.exec-label: "paperless"
      docker-volume-backup.archive-pre: /bin/sh -c 'pg_dumpall -U paperless --clean --file=/backup/paperless_db.sql'
    volumes:
      - /opt/appdata/paperless/db/pg16:/var/lib/postgresql/data
      - /opt/appdata/paperless/db/backup:/backup
    networks:
      - default
    secrets:
      - db_pass

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:${PAPERLESS_VERSION:-latest}
    container_name: paperless
    restart: unless-stopped
    depends_on:
      - db
      - broker
    user: "1000:1000"
    env_file:
      - ./paperless.env
      - /opt/appdata/paperless/secrets/secrets.env
    volumes:
      - /opt/appdata/paperless/data:/usr/src/paperless/data
      - /opt/terminal_dogma/AppData/paperless/media:/usr/src/paperless/media
      - type: volume
        source: transfer
        target: /usr/src/paperless/export
        volume:
          nocopy: true
          subpath: export
      - type: volume
        source: transfer
        target: /usr/src/paperless/consume
        volume:
          nocopy: true
          subpath: import        
    networks:
      - default
      - homelab
    secrets:
      - db_pass

volumes:
  redis-data:
  transfer:
    driver: local
    driver_opts:
      type: nfs
      o: addr=terminal-dogma.local,nolock,soft,nfsvers=4
      device: :/mnt/DataPool/PaperlessTransfer

networks:
  default:

secrets:
  db_pass:
    file: /opt/appdata/paperless/secrets/db_pass
