include:
  - ../common/networks.yaml

services:
  meilisearch: # Port 7700
    image: getmeili/meilisearch:v1.15
    container_name: ba-search
    restart: unless-stopped
    labels:
      wud.watch: false
    env_file:
      - /opt/appdata/bar-assistant/secrets/bar.env
    environment:
      MEILI_NO_ANALYTICS: true
      MEILI_ENV: production
    networks:
      - homelab
      - default
    volumes:
      - meili_data:/meili_data

  # Optional, but recommended
  redis:
    image: redis
    restart: unless-stopped
    labels:
      wud.watch: false
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    networks:
      - default

  bar-assistant: # Port 8080
    image: barassistant/server:${BAR_VERSION:-latest}
    container_name: bar-assistant
    restart: unless-stopped
    depends_on:
      - meilisearch
      - redis
    labels:
      wud.tag.include: '^\d+\.\d+\.\d+$'
      docker-volume-backup.exec-label: "bar-assistant"
      docker-volume-backup.archive-pre: /bin/sh -c 'php artisan bar:full-backup'
    env_file:
      - /opt/appdata/bar-assistant/secrets/bar.env
    environment:
      MEILISEARCH_HOST: http://meilisearch:7700
      REDIS_HOST: redis
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
    networks:
      - homelab
      - default
    volumes:
      - bar_data:/var/www/cocktails/storage/bar-assistant
      - /opt/appdata/bar-assistant/backups:/var/www/cocktails/storage/bar-assistant/backups

  salt-rim: # Port 8080
    image: barassistant/salt-rim:${SALTRIM_VERSION:-latest}
    container_name: salt-rim
    restart: unless-stopped
    depends_on:
      - bar-assistant
    labels:
      wud.tag.include: '^\d+\.\d+\.\d+$'
    env_file:
      - /opt/appdata/bar-assistant/secrets/bar.env
    networks:
      - homelab
      - default

volumes:
  meili_data:
  bar_data:

networks:
  default:
