include:
  - ../common/networks.yaml
services:
  beszel:
    image: henrygd/beszel:${VERSION:-latest}
    container_name: beszel
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 8090:8090
    labels:
      wud.tag.include: '^\d+\.\d+\.\d+$'
    volumes:
      - /opt/appdata/beszel:/beszel_data
      - /opt/terminal_dogma/AppData/beszel:/beszel_data/backups
    networks:
      - homelab
  beszel-agent:
    image: henrygd/beszel-agent:${VERSION:-latest}
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    labels:
      wud.tag.include: '^\d+\.\d+\.\d+$'
    env_file: /opt/appdata/beszel-agent/beszel-agent.env
    environment:
      PORT: 45876
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk/.beszel:/extra-filesystems/sda1:ro
