include:
  - ../common/networks.yaml
services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 8090:8090
    volumes:
      - /opt/appdata/beszel:/beszel_data
    networks:
      - homelab
  beszel-agent:
    image: henrygd/beszel-agent
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    env_file: /opt/appdata/beszel-agent/beszel-agent.env
    environment:
      PORT: 45876
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk/.beszel:/extra-filesystems/sda1:ro
  backup:
    image: offen/docker-volume-backup:v2.46.1
    restart: unless-stopped
    env_file: ./backup.env
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /opt/appdata/beszel/backups:/backup/beszel:ro
      - /opt/terminal_dogma/AppData/beszel:/archive