include:
  - ../common/networks.yaml
services:
  spoolman: # Port 8000
    image: ghcr.io/donkie/spoolman:latest
    container_name: spoolman
    restart: unless-stopped
    environment:
      TZ: America/Los_Angeles
    networks:
      - homelab
    volumes:
      - /opt/appdata/spoolman/data:/home/app/.local/share/spoolman
