services:
  octoeverywhere-bambu-connect:
    image: octoeverywhere/octoeverywhere:latest
    env_file: /opt/appdata/octoeverywhere/bambu_x1c_feanor.env
    environment:
        # Requried to set the docker conntainer in Bambu Connect mode.
      COMPANION_MODE: bambu
    volumes:
      - /opt/appdata/octoeverywhere/data:/data
