include:
  - ../common/networks.yaml

services:
  db:
    image: postgres:14
    container_name: servarr-db
    restart: unless-stopped
    user: "1000:1000"
    environment:
      POSTGRES_USER: servarr
      POSTGRES_PASSWORD_FILE: /run/secrets/db_pass
    volumes:
      - /opt/appdata/servarr/db/pg14:/var/lib/postgresql/data
    networks:
      - default
    secrets:
      - db_pass
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Los_Angeles
      RADARR__POSTGRES__HOST: db
      RADARR__POSTGRES__PORT: 5432
      RADARR__POSTGRES__USER: servarr
      RADARR__POSTGRES__PASSWORD: ${DB_PASS}
    volumes:
      - central-dogma:/data
      - /opt/appdata/servarr/radarr:/config
    networks:
      - default
      - homelab
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: always
    depends_on:
      - db
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Los_Angeles
      SONARR__POSTGRES__HOST: db
      SONARR__POSTGRES__PORT: 5432
      SONARR__POSTGRES__USER: servarr
      SONARR__POSTGRES__PASSWORD: ${DB_PASS}
    volumes:
      - central-dogma:/data
      - /opt/appdata/servarr/sonarr:/config
    networks:
      - default
      - homelab

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: always
    depends_on:
      - db
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Los_Angeles
      POSTGRES_ENABLED: True
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: servarr
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - central-dogma:/data
      - /opt/appdata/servarr/bazarr:/config
    networks:
      - default
      - homelab
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: always
    depends_on:
      - db
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Los_Angeles
      PROWLARR__POSTGRES__HOST: db
      PROWLARR__POSTGRES__PORT: 5432
      PROWLARR__POSTGRES__USER: servarr
      PROWLARR__POSTGRES__PASSWORD: ${DB_PASS}
    volumes:
      - /opt/appdata/servarr/prowlarr:/config
    networks:
      - default
      - homelab

  maintainerr: # Port 6246 
    image: ghcr.io/maintainerr/maintainerr:v2.20
    container_name: maintainerr
    restart: unless-stopped
    user: 1000:1000
    environment:
      TZ: America/Los_Angeles
    volumes:
      - /opt/appdata/servarr/maintainerr:/opt/data
    networks:
      - default
      - homelab

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: always
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Los_Angeles
    volumes:
      - central-dogma:/data
      - /opt/appdata/servarr/sabnzbd:/config
    networks:
      - default
      - homelab
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    restart: always
    env_file: /etc/homelab/transmission.env
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Los_Angeles
      USER: admin
    ports:
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - central-dogma:/data
      - /opt/appdata/servarr/transmission:/config
    networks:
      - default
      - homelab

volumes:
  central-dogma:
    driver: local
    driver_opts:
      type: nfs
      o: addr=central-dogma.local,nolock,soft,nfsvers=4
      device: :/volume1/Media

secrets:
  db_pass:
    file: /etc/homelab/servarr/secrets/db_pass

networks:
  default: