include:
  - ../common/networks.yaml

services:
  db:
    image: postgres:14
    container_name: servarr-db
    restart: unless-stopped
    user: "1000:1000"
    environment:
      POSTGRES_USER: servarr
      POSTGRES_PASSWORD_FILE: /run/secrets/db_pass
    labels:
      wud.watch: false
      docker-volume-backup.exec-label: "servarr"
      docker-volume-backup.archive-pre: /bin/sh -c 'pg_dumpall -U servarr --clean --file=/backup/servarr_db.sql'
    volumes:
      - /opt/appdata/servarr/db/pg14:/var/lib/postgresql/data
      - /opt/appdata/servarr/db/backup:/backup
    networks:
      - default
    secrets:
      - db_pass
  radarr:
    image: lscr.io/linuxserver/radarr:${RADARR_VERSION:-latest}
    container_name: radarr
    restart: unless-stopped
    depends_on:
      - db
    labels:
      wud.tag.include: '^\d+\.\d+\.\d+$'
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Los_Angeles
      RADARR__POSTGRES__HOST: db
      RADARR__POSTGRES__PORT: 5432
      RADARR__POSTGRES__USER: servarr
      RADARR__POSTGRES__PASSWORD: ${DB_PASS}
    volumes:
      - central-dogma:/data
      - /opt/appdata/servarr/radarr:/config
      - /opt/terminal_dogma/AppData/servarr/radarr:/backups
    networks:
      - default
      - homelab
  sonarr:
    image: lscr.io/linuxserver/sonarr:${SONARR_VERSION:-latest}
    container_name: sonarr
    restart: always
    depends_on:
      - db
    labels:
      wud.tag.include: '^\d+\.\d+\.\d+$'
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Los_Angeles
      SONARR__POSTGRES__HOST: db
      SONARR__POSTGRES__PORT: 5432
      SONARR__POSTGRES__USER: servarr
      SONARR__POSTGRES__PASSWORD: ${DB_PASS}
    volumes:
      - central-dogma:/data
      - /opt/appdata/servarr/sonarr:/config
      - /opt/terminal_dogma/AppData/servarr/sonarr:/backups
    networks:
      - default
      - homelab

  bazarr:
    image: lscr.io/linuxserver/bazarr:${BAZARR_VERSION:-latest}
    container_name: bazarr
    restart: always
    depends_on:
      - db
    labels:
      wud.tag.include: '^\d+\.\d+\.\d+$'
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Los_Angeles
      POSTGRES_ENABLED: True
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: servarr
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - central-dogma:/data
      - /opt/appdata/servarr/bazarr:/config
      - /opt/terminal_dogma/AppData/servarr/bazarr:/backups
    networks:
      - default
      - homelab
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:${PROWLARR_VERSION:-latest}
    container_name: prowlarr
    restart: always
    depends_on:
      - db
    labels:
      wud.tag.include: '^\d+\.\d+\.\d+$'
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Los_Angeles
      PROWLARR__POSTGRES__HOST: db
      PROWLARR__POSTGRES__PORT: 5432
      PROWLARR__POSTGRES__USER: servarr
      PROWLARR__POSTGRES__PASSWORD: ${DB_PASS}
    volumes:
      - /opt/appdata/servarr/prowlarr:/config
      - /opt/terminal_dogma/AppData/servarr/prowlarr:/backups
    networks:
      - default
      - homelab

  maintainerr: # Port 6246 
    image: ghcr.io/maintainerr/maintainerr:${MAINTAINERR_VERSION:-latest}
    container_name: maintainerr
    restart: unless-stopped
    user: 1000:1000
    labels:
      wud.tag.include: '^\d+\.\d+\.\d+$'
    environment:
      TZ: America/Los_Angeles
    volumes:
      - /opt/appdata/servarr/maintainerr:/opt/data
    networks:
      - default
      - homelab

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: always
    labels:
      wud.tag.include: '^\d+\.\d+\.\d+-ls\d+$'
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Los_Angeles
    volumes:
      - central-dogma:/data
      - /opt/appdata/servarr/sabnzbd:/config
      - /opt/terminal_dogma/AppData/servarr/sabnzbd:/backups
    networks:
      - default
      - homelab
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    restart: always
    labels:
      wud.tag.include: '^\d+\.\d+\.\d+-r\d+-ls\d+$'
    env_file: /opt/appdata/servarr/secrets/transmission.env
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Los_Angeles
      USER: admin
    ports:
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - central-dogma:/data
      - /opt/appdata/servarr/transmission:/config
    networks:
      - default
      - homelab

volumes:
  central-dogma:
    driver: local
    driver_opts:
      type: nfs
      o: addr=central-dogma.local,nolock,soft,nfsvers=4
      device: :/volume1/Media

secrets:
  db_pass:
    file: /opt/appdata/servarr/secrets/db_pass

networks:
  default: